# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('impressions_negated', models.TextField(blank=True, max_length=5000, null=True)),
                ('impressions_positive', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
