# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20160607_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 22, 30, 20, 65577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date2',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 22, 30, 20, 65634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date3',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 22, 30, 20, 65679, tzinfo=utc)),
        ),
    ]
