# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20160607_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date1',
        ),
        migrations.AlterField(
            model_name='report',
            name='date2',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 5, 0, 46, 946519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date3',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 5, 0, 46, 946569, tzinfo=utc)),
        ),
    ]
