# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20160610_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date1',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 5, 9, 51, 832588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date2',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 5, 9, 51, 832643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date3',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 5, 9, 51, 832686, tzinfo=utc)),
        ),
    ]
