# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20160610_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accession1',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='accession2',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='accession3',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='clinical_statement',
            field=models.CharField(max_length=5000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='impression_all1',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='impression_all2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='impression_all3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='mrn',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.TextField(blank=True, help_text='Format is MM-DD-YYYY', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date2',
            field=models.TextField(blank=True, help_text='Format is MM-DD-YYYY', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date3',
            field=models.TextField(blank=True, help_text='Format is MM-DD-YYYY', max_length=128, null=True),
        ),
    ]
