# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160606_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date1',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
